server:
  port: 80
  servlet:
    session:
      timeout: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxxx/download?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: xxxxx
  rabbitmq:
    host: xxxxx
  freemarker:
    suffix: .html
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
aliyun:
    sms:
      accessKeyId: XXX
      accessKeySecret: XXXXX
      template_code: SMS_151178730
      sign_name: 个人学习笔记
qiniu:
  accessKey: XXXX
  secretKey: XXX
  bucket:   download
  path: XXX.bkt.clouddn.com